"""myData & sampleData tables

Revision ID: 51e12f451556
Revises: d60a36f8dd2f
Create Date: 2022-02-25 01:23:42.532835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e12f451556'
down_revision = 'd60a36f8dd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_room', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('day_part', sa.Integer(), nullable=False),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_room', sa.Integer(), nullable=False),
    sa.Column('day_part', sa.Integer(), nullable=False),
    sa.Column('time_diff', sa.Integer(), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_data')
    op.drop_table('my_data')
    # ### end Alembic commands ###
