"""users and rooms

Revision ID: 67d621aee1b4
Revises: 51e12f451556
Create Date: 2022-04-17 19:53:32.000797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d621aee1b4'
down_revision = '51e12f451556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('e_mail', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id_room', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_room')
    )
    op.alter_column('my_data', 'id_room',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'my_data', 'rooms', ['id_room'], ['id_room'])
    op.alter_column('sample_data', 'id_room',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'sample_data', 'rooms', ['id_room'], ['id_room'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample_data', type_='foreignkey')
    op.alter_column('sample_data', 'id_room',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'my_data', type_='foreignkey')
    op.alter_column('my_data', 'id_room',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
